// GameEventListener.java

 
/** 
 *
 * @author  Sean Bridges
 * @version 1.0
 *
 *  A GameEvent represents a significant event in the life cycle of a game.
 *  Events include, GameStarted, GameStopped, GameRestarted, and moves.
 *  Game events are generated by the GameMaster. 
 */
public interface GameEventListener 
{
  
	/**
	 * The game has started.
	 */
	public void gameStarted();
  
	/**
	 * The game has stopped
	 */
	public void gameStoped();
  
	/**  
	 * The game has been restarted.
	 */
	public void gameRestarted();
  
	/** 
	 * A player has moved.
	 */
	public void moveMade(Move aMove);
  
}
